
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/finansys
    password: docker
    username: postgres
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true